#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-dnsjava
Version  : 2.1.7
Release  : 1
URL      : https://github.com/dnsjava/dnsjava/archive/v2.1.7.tar.gz
Source0  : https://github.com/dnsjava/dnsjava/archive/v2.1.7.tar.gz
Source1  : https://repo1.maven.org/maven2/dnsjava/dnsjava/2.1.7/dnsjava-2.1.7.jar
Source2  : https://repo1.maven.org/maven2/dnsjava/dnsjava/2.1.7/dnsjava-2.1.7.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: mvn-dnsjava-data = %{version}-%{release}

%description
dnsjava v2.0
http://www.dnsjava.org/
Author:
Brian Wellington (bwelling@xbill.org)
March 12, 2004

%package data
Summary: data components for the mvn-dnsjava package.
Group: Data

%description data
data components for the mvn-dnsjava package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/dnsjava/dnsjava/2.1.7
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/dnsjava/dnsjava/2.1.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/dnsjava/dnsjava/2.1.7
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/dnsjava/dnsjava/2.1.7


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/dnsjava/dnsjava/2.1.7/dnsjava-2.1.7.jar
/usr/share/java/.m2/repository/dnsjava/dnsjava/2.1.7/dnsjava-2.1.7.pom
